import type { createCn } from "cn/engine";

/** Merge tables generated by `cn build` (next.config.mjs → withCn) before every dev/build/typegen; gitignored. */
declare const tables: Parameters<typeof createCn>[0];
export default tables;
