import type { createCn } from "cn/engine";

/** Merge tables generated by `cn build` (config/next.ts → withCn) before every dev/build/typegen; gitignored. */
declare const tables: Parameters<typeof createCn>[0];
export default tables;
