/** Assistant-local English copy; the storefront language and product facts do not change. */
import type { AssistantCopy } from "../es/assistant.ts";

export const launcherCopy = {
  launcherLabel: "Open the Pequeverso assistant",
  launcherUnread: "There is a new answer",
};

export const assistantCopy: AssistantCopy = {
  name: "Pequeverso Assistant",
  aiDisclosure: "AI assistant. Uses information from the store.",
  privacyNote: "Do not enter personal information about you or your children. ",
  privacyLink: "How we handle your messages",
  greetingTitle: "Hi! How can I help?",
  greetingBody:
    "Ask what each material includes, which ages it is for, how to print it or use it at home. I answer using information from the store.",
  startersLabel: "Questions to get started",
  starters: [
    "What does Grafismo Fonético include?",
    "Is it suitable for a 4-year-old?",
    "How do I print it and use it at home?",
    "How do I receive the material after buying it?",
  ],
  transcriptLabel: "Conversation with the assistant",
  you: "You",
  assistant: "Assistant",
  composerLabel: "Write your question",
  composerPlaceholder: "Write your question…",
  composerHint: "Enter to send · Shift + Enter for a new line",
  send: "Send question",
  stop: "Stop answer",
  stopping: "Stopping…",
  charactersLeft: (count) => (count === 1 ? "1 character left" : `${count} characters left`),
  tooLong: (max) => `Your question exceeds the ${max}-character limit.`,
  thinking: "Thinking…",
  answerReady: "Answer ready.",
  answerStopped: "Answer stopped.",
  answerInterrupted: "Answer interrupted.",
  answerFailed: "The answer could not be completed.",
  jumpToLatest: "Go to the latest answer",
  partialLabel: "Incomplete answer",
  inProgressLabel: "Answer in progress, not confirmed yet",
  cancelledTitle: "You stopped the answer.",
  interruptedTitle: "The connection was lost before the answer finished.",
  failedTitle: "I could not complete the answer.",
  retry: "Retry",
  dismiss: "Dismiss notice",
  copy: "Copy answer",
  copied: "Copied",
  copyFailed: "Could not copy",
  productsLabel: "Products mentioned",
  compareLabel: "Comparison",
  viewProduct: "View the material",
  purchaseOptions: "View purchase options",
  opensInNewTab: "(opens in a new tab)",
  ageRange: "Age",
  price: "Price",
  priceVerified: (date) => `Price confirmed on ${date}`,
  priceUnverified: "Check the current price on the material's page",
  resourcesLabel: "Includes",
  pages: (count) => (count === 1 ? "1 page" : `${count} pages`),
  resourceCount: (count) => (count === 1 ? "1 resource" : `${count} resources`),
  sourcesLabel: (count) => (count === 1 ? "1 source" : `${count} sources`),
  sourcesHint: "Store information used in this answer",
  linksLabel: "Useful links",
  followUpsLabel: "You can ask",
  notices: {
    answer_replaced:
      "I could not confirm that answer using information from the store, so I am showing a safe answer.",
    payment_data_refused:
      "For your safety, do not enter card details here. Payment happens only on Hotmart's secure page.",
    contact_data_redacted: "We hid contact details from your message to protect your privacy.",
    language_unsupported: "I currently answer in Spanish and English.",
  },
  clear: "New conversation",
  clearConfirmTitle: "Start again?",
  clearConfirmBody: "This conversation will be deleted and you will not be able to recover it.",
  clearConfirm: "Delete",
  clearCancel: "Cancel",
  clearing: "Deleting…",
  expand: "Expand panel",
  restore: "Reduce panel",
  minimize: "Minimize assistant",
  languageLabel: "Assistant language",
  connecting: "Connecting to the assistant…",
  reconnect: "Retry connection",
  expiredNotice: "Your previous conversation expired. You can start a new one.",
  offlineTitle: "We could not connect to the assistant.",
  offlineBody: "Check your connection and try again. The store keeps working as usual.",
  unavailableTitle: "The assistant is unavailable right now.",
  unavailableBody: {
    assistant_disabled: "You can keep browsing the store or contact us through Support.",
    budget_exhausted:
      "It has reached its usage limit for now. You can keep browsing the store or contact us through Support.",
    catalog_unavailable:
      "I cannot access the store information right now. You can keep browsing or contact us through Support.",
  },
  supportLink: "Go to Support",
  errors: {
    invalid_request: "I could not process that question. Try phrasing it differently.",
    origin_denied: "The assistant does not accept questions from this page.",
    csrf_failed: "The session was renewed. Send your question again.",
    session_expired: "The session expired. Send your question again.",
    rate_limited: "You asked several questions quickly. Wait a moment before continuing.",
    busy: "The assistant is busy. Try again in a few seconds.",
    run_in_progress: "I am still answering your previous question.",
    idempotency_conflict: "I could not resend that question. Write it again.",
    run_not_found: "That answer has already finished.",
    budget_exhausted: "The assistant reached its usage limit for now.",
    assistant_disabled: "The assistant is unavailable right now.",
    catalog_unavailable: "I cannot access the store information right now.",
    provider_unavailable: "The answer service is unavailable. Try again later.",
    generation_failed: "I could not generate the answer. You can retry.",
    timeout: "The answer took too long. You can retry.",
    dependency_unavailable: "The assistant had a temporary problem. Try again later.",
    not_found: "I could not find what you were looking for.",
    network: "The connection was lost. Check your network and try again.",
    protocol: "I received an unexpected response from the server. Try again.",
  },
};
